@Lil.TimeTracker_HostAddress = https://localhost:7226

@AcessToken=CfDJ8PnSz0LdR2xDqa29P4MGHIOfY_RlLxZIDneSgryqr0cb4RE7nOzW3Sstm40wfcInhA6PfoafmqiJVCWSQnRKgXawtahCl5twun_623np6wj81Bvu3Au4I02tlIyqjI9mynOI58i5rKjexhQPd_J90YqW76EM51egdexrE-GQK3WKRyDc00NbHqXhx0SovNoQMF5BBw_HJSPJUSt4GhtuTDD5dsJhmVNJzA5RmMoOp4ZxgtKCtDrVSh94fetaSSnjQzQPbbo_4klMEEbcEYqQXONlezFKaQklOUjN_YPWzmtJ3O4RkvtG8G57hFVk_RN4i9nf9lm0tCAkMiuNAtM5Xe_fkIVDcqHfMNPTu_Fs5Wi9p-bvbNSp0upWU0nOHhbRx_WS_d1-JSGh4ruIi02OdOSiz8Q9NUQls4_z-eaCZIgKkB3_QdNO2KeHsDbSOgrZDvjYMsB4GiMehj7Dvm_1m2BdXUReUjywvnv22fWICOBqYBgjxRCxTNb8WOVLcmLj2brYlc6rj0yOMjUvD0ZOt4J7emn4BiY9WJCXSk0d4dLYSfSHpKGvTakHM7p47fqLsnl5L25Kw4h3kWuVZzTH7rA_tG6izPhPNxZyKu5sMoLdHe2sPT0fjbBxADzxHDwN-GqVFgO2dPT40E4szBbfNggl6REv3REcieB67SscBtwLocX9woq4AmoVoNTkDjielw

POST {{Lil.TimeTracker_HostAddress}}/identity/register
Content-Type: application/json

{
    "email": "angel@test.com",
    "password": "@Password123"
}

###

POST {{Lil.TimeTracker_HostAddress}}/identity/login
Content-Type: application/json

{
    "email": "angel@test.com",
    "password": "@Password123"
}

###

GET {{Lil.TimeTracker_HostAddress}}/api/Employee
Authorization: Bearer {{AcessToken}}
###
